export enum QbsCommandKey {
    AutoRestartSession = 'qbs.autoRestartSession',
    Build = 'qbs.build',
    BuildProduct = 'qbs.buildProduct',
    BuildSubProject = 'qbs.buildSubProject',
    Cancel = 'qbs.cancel',
    Clean = 'qbs.clean',
    CleanProduct = 'qbs.cleanProduct',
    CleanSubProject = 'qbs.cleanSubProject',
    Debug = 'qbs.debug',
    DetectProfiles = 'qbs.detectProfiles',
    GetRunEnvironment = 'qbs.getRunEnvironment',
    Install = 'qbs.install',
    Rebuild = 'qbs.rebuild',
    Resolve = 'qbs.resolve',
    ResolveWithForceExecution = 'qbs.resolveWithForceProbesExecution',
    RestoreProject = 'qbs.restoreProject',
    Run = 'qbs.run',
    SelectBuild = 'qbs.selectBuild',
    SelectConfiguration = 'qbs.selectConfiguration',
    SelectDebugger = 'qbs.selectDebugger',
    SelectProfile = 'qbs.selectProfile',
    SelectProject = 'qbs.selectProject',
    SelectRun = 'qbs.selectRun',
    StartSession = 'qbs.startSession',
    StopSession = 'qbs.stopSession',
    EditConfiguration = 'qbs.editConfiguration',
}
