name: CI (Ubuntu)

on:
  push:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
    - run: npm install
    - run: npm run compile

  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
    - run: npm install
    - run: xvfb-run -a npm run test
